name: Start Mining

on:
  workflow_dispatch:

jobs:
  start-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Extract server info from secrets
        run: |
          echo "$SERVERS_JSON" > servers.json
        env:
          SERVERS_JSON: ${{ secrets.SERVERS_JSON }}

      - name: Generate and run SSH start script
        run: |
          echo "#!/bin/bash" > start.sh
          while IFS= read -r server; do
            user=$(echo "$server" | jq -r '.username')
            pass=$(echo "$server" | jq -r '.password')
            host=$(echo "$server" | jq -r '.host')
            echo "echo Starting on $host" >> start.sh
            echo "sshpass -p \"$pass\" ssh -o StrictHostKeyChecking=no $user@$host 'bash <(curl -s https://raw.githubusercontent.com/amosgansweet/s10-start-stop/refs/heads/main/start.sh?token=GHSAT0AAAAAADBOTY2VIZDRBYDVOTPZ734IZ77O4GA)'" >> start.sh
            
          done < <(jq -c '.[]' servers.json)
          chmod +x start.sh
          ./start.sh
