name: Stop s10webh2

on:
  workflow_dispatch:

jobs:
  stop-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Extract server info from secrets
        run: |
          echo "$SERVERS_JSON" > servers.json
        env:
          SERVERS_JSON: ${{ secrets.SERVERS_JSON }}

      - name: Generate and run SSH stop script
        run: |
          echo "#!/bin/bash" > stop.sh
          while IFS= read -r server; do
            user=$(echo "$server" | jq -r '.username')
            pass=$(echo "$server" | jq -r '.password')
            host=$(echo "$server" | jq -r '.host')
            echo "echo Stopping on $host" >> stop.sh
            echo "sshpass -p \"$pass\" ssh -o StrictHostKeyChecking=no $user@$host 'bash <(curl -s https://raw.githubusercontent.com/amosgansweet/s10-start-stop/main/stop.sh)'" >> stop.sh
            
          done < <(jq -c '.[]' servers.json)
          chmod +x stop.sh
          ./stop.sh
